version: 2
jobs:
build:
  working_directory: ~/student-test
  docker:
    - image: circleci/node:8-browsers
  steps:
    - checkout
    - restore_cache:
        key: student-test-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: student-test-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - "node_modules"
    - run: npm run test -- --watch=false